name: Deploy Release

on:
  release:
    types: [created]

# TODO: Check if hotfix is in the tag name
# Get the target branch from there
jobs:
  deploy:
    name: Deploy new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit SHA for release
        id: get_commit_sha
        run: echo name=sha-$(git rev-parse HEAD~)

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Yarn install
        run: yarn install --frozen-lockfile
      
      - name: Docker Release
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: docker-release
          all: 'true'
          parallel: 3

      