name: Deploy Release

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Yarn install
        run: yarn install --frozen-lockfile
      
      - name: Build
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build
          all: 'true'
          parallel: 3

      