name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
      - name: Hello Step
        run: echo "Hello ${{ github.event.inputs.name }}"

    release:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: git config
          run: |
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

        - run: yarn install

        - run: yarn release ${{ inputs.release_type }} --ci
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}