name: Create Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Test"
        default: "Test"

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - name: Hello Step
          run: echo "Hello ${{ github.event.inputs.name }}"