name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
    release:
      name: Generate and Create Release
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: git config
          run: |
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

        - name: Setup Node.js
          id: setup-node
          uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'yarn'

        - name: Yarn install
          run: yarn install --frozen-lockfile

        - name: Release It
          run: yarn release ${{ inputs.release_type }} --ci
          env:
            GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}